apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: artifactory
  name: artifactory
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      run: artifactory
  template:
    metadata:
      labels:
        run: artifactory
    spec:
      containers:
      - image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
        name: artifactory
		
### UPDATE PROBES!
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 5"]
---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: artifactory
  name: artifactory-port
  namespace: default
spec:
  selector:
    run: artifactory
  ports:
    - port: 8081
      name: http
  type: NodePort