apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: artifactory
  name: artifactory
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      run: artifactory
  template:
    metadata:
      labels:
        run: artifactory
    spec:
      containers:
      - image: docker.bintray.io/jfrog/artifactory-oss:5.5.1
        name: artifactory
---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: artifactory
  name: artifactory-port
  namespace: default
spec:
  selector:
    run: artifactory
  ports:
    - port: 8081
      name: http
  type: NodePort