apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: artifactory
  name: artifactory
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      run: artifactory
  template:
    metadata:
      labels:
        run: artifactory
    spec:
      containers:
      - image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
        name: artifactory
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8081
        initialDelaySeconds: 15
        periodSeconds: 20
---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: artifactory
  name: artifactory-port
  namespace: default
spec:
  selector:
    run: artifactory
  ports:
    - port: 8081
      name: http
  type: NodePort