---
defaultBaseImageVersion: latest
stages:
- name: PROD
  inputs:
  - type: job
    stage: CONTAINERIZE
    job: Build Docker image
  triggers:
  - type: stage
  properties:
  - name: CLUSTER_NAMESPACE
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: APP_URL
    value: undefined
    type: text
  - name: REGISTRY_URL
    value: us.icr.io
    type: text
  - name: build_proprties
    value: build.properties
    type: file
  jobs:
  - name: Deploy Artifactory
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      resource_group: ${PROD_RESOURCE_GROUP}
      api_key: ${API_KEY}
      kubernetes_cluster: ${PROD_CLUSTER_NAME}
    script: |
      kubectl apply -f deployment.yml